// tq_exports.h - generated by tools/gen_exports_header.py. DO NOT EDIT BY HAND.
//
// Titan Quest Anniversary Edition 2.10, x86. Exported symbol names checked verbatim against the
// export tables of Engine.dll / Game.dll (tools/tqexports.py); the comment above each macro is
// undname.exe output for that exact string. ZERO ADDRESSES: everything is resolved by name at
// run time (GetModuleHandle + GetProcAddress on modules the game already loaded).
//
// Calling convention: x86 does NOT collapse them. Every <name>_CC below is what the MANGLING says:
//   TQCC_THISCALL  a member (QAE/QBE/UAE/UBE/AAE): `this` in ECX, callee cleans the stack. The mod
//                  calls it through a __thiscall typedef and DETOURS it as
//                  __fastcall(void* self, void* edx_unused, args...) - the same stack shape.
//   TQCC_CDECL     a free function (YA) or a static member (SA).
//   TQCC_DATA      a global, static data or a vftable - the address of the variable.
// <name>_SRET 1 = a class is returned by value: a hidden return pointer is the first stack
// argument after `this`. <name>_REQ 1 = REQUIRED: a miss turns the mod off before any hook.
//
// Names that create, move, delete or persist something are marked WRITE: hooked to observe, never
// called by the mod.

#pragma once

#define TQCC_DATA 0
#define TQCC_THISCALL 1
#define TQCC_CDECL 2
#define TQCC_STDCALL 3
#define TQCC_FASTCALL 4

#define TQ_EXPORT_COUNT 121
#define TQ_EXPORT_REQUIRED_COUNT 30

// ---------------------------------------------------------------------------------------------
// Engine - singleton, frame, database   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// class GAME::Engine * GAME::gEngine
//   global data, data, REQUIRED
#define TQ_ENGINE_GENGINE "?gEngine@GAME@@3PAVEngine@1@A"
#define TQ_ENGINE_GENGINE_MOD "Engine.dll"
#define TQ_ENGINE_GENGINE_CC TQCC_DATA
#define TQ_ENGINE_GENGINE_SRET 0
#define TQ_ENGINE_GENGINE_REQ 1

// public: void __thiscall GAME::Engine::PresentSurface(void)
//   member, __thiscall, REQUIRED
#define TQ_ENGINE_PRESENTSURFACE "?PresentSurface@Engine@GAME@@QAEXXZ"
#define TQ_ENGINE_PRESENTSURFACE_MOD "Engine.dll"
#define TQ_ENGINE_PRESENTSURFACE_CC TQCC_THISCALL
#define TQ_ENGINE_PRESENTSURFACE_SRET 0
#define TQ_ENGINE_PRESENTSURFACE_REQ 1

// private: void __thiscall GAME::Engine::LoadMainDatabase(void)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_ENGINE_LOADMAINDATABASE "?LoadMainDatabase@Engine@GAME@@AAEXXZ"
#define TQ_ENGINE_LOADMAINDATABASE_MOD "Engine.dll"
#define TQ_ENGINE_LOADMAINDATABASE_CC TQCC_THISCALL
#define TQ_ENGINE_LOADMAINDATABASE_SRET 0
#define TQ_ENGINE_LOADMAINDATABASE_REQ 1

// private: bool __thiscall GAME::Engine::LoadDatabase(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_ENGINE_LOADDATABASE "?LoadDatabase@Engine@GAME@@AAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"
#define TQ_ENGINE_LOADDATABASE_MOD "Engine.dll"
#define TQ_ENGINE_LOADDATABASE_CC TQCC_THISCALL
#define TQ_ENGINE_LOADDATABASE_SRET 0
#define TQ_ENGINE_LOADDATABASE_REQ 1

// public: unsigned int __thiscall GAME::Engine::GetDatabaseArchiveChecksum(void)
//   member, __thiscall, REQUIRED
#define TQ_ENGINE_GETDATABASEARCHIVECHECKSUM "?GetDatabaseArchiveChecksum@Engine@GAME@@QAEIXZ"
#define TQ_ENGINE_GETDATABASEARCHIVECHECKSUM_MOD "Engine.dll"
#define TQ_ENGINE_GETDATABASEARCHIVECHECKSUM_CC TQCC_THISCALL
#define TQ_ENGINE_GETDATABASEARCHIVECHECKSUM_SRET 0
#define TQ_ENGINE_GETDATABASEARCHIVECHECKSUM_REQ 1

// public: bool __thiscall GAME::Engine::HasLoadedCustomDatabase(void)
//   member, __thiscall, optional
#define TQ_ENGINE_HASLOADEDCUSTOMDATABASE "?HasLoadedCustomDatabase@Engine@GAME@@QAE_NXZ"
#define TQ_ENGINE_HASLOADEDCUSTOMDATABASE_MOD "Engine.dll"
#define TQ_ENGINE_HASLOADEDCUSTOMDATABASE_CC TQCC_THISCALL
#define TQ_ENGINE_HASLOADEDCUSTOMDATABASE_SRET 0
#define TQ_ENGINE_HASLOADEDCUSTOMDATABASE_REQ 0

// public: bool __thiscall GAME::Engine::InitializeMod(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, optional
#define TQ_ENGINE_INITIALIZEMOD "?InitializeMod@Engine@GAME@@QAE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z"
#define TQ_ENGINE_INITIALIZEMOD_MOD "Engine.dll"
#define TQ_ENGINE_INITIALIZEMOD_CC TQCC_THISCALL
#define TQ_ENGINE_INITIALIZEMOD_SRET 0
#define TQ_ENGINE_INITIALIZEMOD_REQ 0

// public: class GAME::GameInfo * __thiscall GAME::Engine::GetGameInfo(void)
//   member, __thiscall, optional
#define TQ_ENGINE_GETGAMEINFO "?GetGameInfo@Engine@GAME@@QAEPAVGameInfo@2@XZ"
#define TQ_ENGINE_GETGAMEINFO_MOD "Engine.dll"
#define TQ_ENGINE_GETGAMEINFO_CC TQCC_THISCALL
#define TQ_ENGINE_GETGAMEINFO_SRET 0
#define TQ_ENGINE_GETGAMEINFO_REQ 0

// public: bool __thiscall GAME::Engine::IsNetworkClient(void)
//   member, __thiscall, optional
#define TQ_ENGINE_ISNETWORKCLIENT "?IsNetworkClient@Engine@GAME@@QAE_NXZ"
#define TQ_ENGINE_ISNETWORKCLIENT_MOD "Engine.dll"
#define TQ_ENGINE_ISNETWORKCLIENT_CC TQCC_THISCALL
#define TQ_ENGINE_ISNETWORKCLIENT_SRET 0
#define TQ_ENGINE_ISNETWORKCLIENT_REQ 0

// public: bool __thiscall GAME::Engine::IsNetworkServer(void)
//   member, __thiscall, optional
#define TQ_ENGINE_ISNETWORKSERVER "?IsNetworkServer@Engine@GAME@@QAE_NXZ"
#define TQ_ENGINE_ISNETWORKSERVER_MOD "Engine.dll"
#define TQ_ENGINE_ISNETWORKSERVER_CC TQCC_THISCALL
#define TQ_ENGINE_ISNETWORKSERVER_SRET 0
#define TQ_ENGINE_ISNETWORKSERVER_REQ 0

// public: class GAME::GraphicsEngine * __thiscall GAME::Engine::GetGraphicsEngine(void)const 
//   member, __thiscall, optional
#define TQ_ENGINE_GETGRAPHICSENGINE "?GetGraphicsEngine@Engine@GAME@@QBEPAVGraphicsEngine@2@XZ"
#define TQ_ENGINE_GETGRAPHICSENGINE_MOD "Engine.dll"
#define TQ_ENGINE_GETGRAPHICSENGINE_CC TQCC_THISCALL
#define TQ_ENGINE_GETGRAPHICSENGINE_SRET 0
#define TQ_ENGINE_GETGRAPHICSENGINE_REQ 0

// public: class GAME::FileSystem * __thiscall GAME::Engine::GetFileSystem(void)
//   member, __thiscall, optional
#define TQ_ENGINE_GETFILESYSTEM "?GetFileSystem@Engine@GAME@@QAEPAVFileSystem@2@XZ"
#define TQ_ENGINE_GETFILESYSTEM_MOD "Engine.dll"
#define TQ_ENGINE_GETFILESYSTEM_CC TQCC_THISCALL
#define TQ_ENGINE_GETFILESYSTEM_SRET 0
#define TQ_ENGINE_GETFILESYSTEM_REQ 0

// public: bool __thiscall GAME::FileSystem::AddSource(enum GAME::FileSystem::Partition,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,char const *,bool,bool,bool)
//   member, __thiscall, optional
#define TQ_ENGINE_FS_ADDSOURCE "?AddSource@FileSystem@GAME@@QAE_NW4Partition@12@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD_N33@Z"
#define TQ_ENGINE_FS_ADDSOURCE_MOD "Engine.dll"
#define TQ_ENGINE_FS_ADDSOURCE_CC TQCC_THISCALL
#define TQ_ENGINE_FS_ADDSOURCE_SRET 0
#define TQ_ENGINE_FS_ADDSOURCE_REQ 0

// public: float __thiscall GAME::Engine::GetUIScale(void)const 
//   member, __thiscall, optional
#define TQ_ENGINE_GETUISCALE "?GetUIScale@Engine@GAME@@QBEMXZ"
#define TQ_ENGINE_GETUISCALE_MOD "Engine.dll"
#define TQ_ENGINE_GETUISCALE_CC TQCC_THISCALL
#define TQ_ENGINE_GETUISCALE_SRET 0
#define TQ_ENGINE_GETUISCALE_REQ 0

// public: class GAME::Options * __thiscall GAME::Engine::GetOptions(void)
//   member, __thiscall, optional
#define TQ_ENGINE_GETOPTIONS "?GetOptions@Engine@GAME@@QAEPAVOptions@2@XZ"
#define TQ_ENGINE_GETOPTIONS_MOD "Engine.dll"
#define TQ_ENGINE_GETOPTIONS_CC TQCC_THISCALL
#define TQ_ENGINE_GETOPTIONS_SRET 0
#define TQ_ENGINE_GETOPTIONS_REQ 0

// public: bool __thiscall GAME::Options::GetBool(enum GAME::Options::BoolName)const 
//   member, __thiscall, optional
#define TQ_ENGINE_OPTIONS_GETBOOL "?GetBool@Options@GAME@@QBE_NW4BoolName@12@@Z"
#define TQ_ENGINE_OPTIONS_GETBOOL_MOD "Engine.dll"
#define TQ_ENGINE_OPTIONS_GETBOOL_CC TQCC_THISCALL
#define TQ_ENGINE_OPTIONS_GETBOOL_SRET 0
#define TQ_ENGINE_OPTIONS_GETBOOL_REQ 0

// ---------------------------------------------------------------------------------------------
// Input - the search field's key gate   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: void __thiscall GAME::Display::HandleKeyEvent(class GAME::InputDevice::ButtonEvent const &)
//   member, __thiscall, optional
#define TQ_INPUT_DISPLAY_HANDLEKEYEVENT "?HandleKeyEvent@Display@GAME@@QAEXABVButtonEvent@InputDevice@2@@Z"
#define TQ_INPUT_DISPLAY_HANDLEKEYEVENT_MOD "Engine.dll"
#define TQ_INPUT_DISPLAY_HANDLEKEYEVENT_CC TQCC_THISCALL
#define TQ_INPUT_DISPLAY_HANDLEKEYEVENT_SRET 0
#define TQ_INPUT_DISPLAY_HANDLEKEYEVENT_REQ 0

// public: unsigned short const * __thiscall GAME::InputDevice::ButtonEvent::GetText(void)const 
//   member, __thiscall, optional
#define TQ_INPUT_BUTTONEVENT_GETTEXT "?GetText@ButtonEvent@InputDevice@GAME@@QBEPBGXZ"
#define TQ_INPUT_BUTTONEVENT_GETTEXT_MOD "Engine.dll"
#define TQ_INPUT_BUTTONEVENT_GETTEXT_CC TQCC_THISCALL
#define TQ_INPUT_BUTTONEVENT_GETTEXT_SRET 0
#define TQ_INPUT_BUTTONEVENT_GETTEXT_REQ 0

// ---------------------------------------------------------------------------------------------
// GameInfo   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: bool __thiscall GAME::GameInfo::GetIsMultiPlayer(void)const 
//   member, __thiscall, optional
#define TQ_GAMEINFO_GETISMULTIPLAYER "?GetIsMultiPlayer@GameInfo@GAME@@QBE_NXZ"
#define TQ_GAMEINFO_GETISMULTIPLAYER_MOD "Engine.dll"
#define TQ_GAMEINFO_GETISMULTIPLAYER_CC TQCC_THISCALL
#define TQ_GAMEINFO_GETISMULTIPLAYER_SRET 0
#define TQ_GAMEINFO_GETISMULTIPLAYER_REQ 0

// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const __thiscall GAME::GameInfo::GetModName(bool)const   [returns by value -> hidden sret pointer]
//   member, __thiscall, optional
#define TQ_GAMEINFO_GETMODNAME "?GetModName@GameInfo@GAME@@QBE?BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z"
#define TQ_GAMEINFO_GETMODNAME_MOD "Engine.dll"
#define TQ_GAMEINFO_GETMODNAME_CC TQCC_THISCALL
#define TQ_GAMEINFO_GETMODNAME_SRET 1
#define TQ_GAMEINFO_GETMODNAME_REQ 0

// ---------------------------------------------------------------------------------------------
// GraphicsEngine / GraphicsCanvas / RenderDevice - the canvas set, optional   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: class GAME::GraphicsCanvas & __thiscall GAME::GraphicsEngine::GetCanvas(void)
//   member, __thiscall, optional
#define TQ_GFX_GETCANVAS "?GetCanvas@GraphicsEngine@GAME@@QAEAAVGraphicsCanvas@2@XZ"
#define TQ_GFX_GETCANVAS_MOD "Engine.dll"
#define TQ_GFX_GETCANVAS_CC TQCC_THISCALL
#define TQ_GFX_GETCANVAS_SRET 0
#define TQ_GFX_GETCANVAS_REQ 0

// public: bool __thiscall GAME::GraphicsEngine::IsDownsizing(void)const 
//   member, __thiscall, optional
#define TQ_GFX_ISDOWNSIZING "?IsDownsizing@GraphicsEngine@GAME@@QBE_NXZ"
#define TQ_GFX_ISDOWNSIZING_MOD "Engine.dll"
#define TQ_GFX_ISDOWNSIZING_CC TQCC_THISCALL
#define TQ_GFX_ISDOWNSIZING_SRET 0
#define TQ_GFX_ISDOWNSIZING_REQ 0

// public: class GAME::GraphicsTexture const * __thiscall GAME::GraphicsEngine::LoadTexture(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)
//   member, __thiscall, optional
#define TQ_GFX_LOADTEXTURE "?LoadTexture@GraphicsEngine@GAME@@QAEPBVGraphicsTexture@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"
#define TQ_GFX_LOADTEXTURE_MOD "Engine.dll"
#define TQ_GFX_LOADTEXTURE_CC TQCC_THISCALL
#define TQ_GFX_LOADTEXTURE_SRET 0
#define TQ_GFX_LOADTEXTURE_REQ 0

// public: int __thiscall GAME::GraphicsCanvas::GetWidth(void)const 
//   member, __thiscall, optional
#define TQ_GFX_CANVAS_GETWIDTH "?GetWidth@GraphicsCanvas@GAME@@QBEHXZ"
#define TQ_GFX_CANVAS_GETWIDTH_MOD "Engine.dll"
#define TQ_GFX_CANVAS_GETWIDTH_CC TQCC_THISCALL
#define TQ_GFX_CANVAS_GETWIDTH_SRET 0
#define TQ_GFX_CANVAS_GETWIDTH_REQ 0

// public: int __thiscall GAME::GraphicsCanvas::GetHeight(void)const 
//   member, __thiscall, optional
#define TQ_GFX_CANVAS_GETHEIGHT "?GetHeight@GraphicsCanvas@GAME@@QBEHXZ"
#define TQ_GFX_CANVAS_GETHEIGHT_MOD "Engine.dll"
#define TQ_GFX_CANVAS_GETHEIGHT_CC TQCC_THISCALL
#define TQ_GFX_CANVAS_GETHEIGHT_SRET 0
#define TQ_GFX_CANVAS_GETHEIGHT_REQ 0

// public: void __thiscall GAME::GraphicsCanvas::RenderRect(class GAME::Rect const &,class GAME::Color const &,class GAME::GraphicsShader2 const *,class GAME::Name const &)
//   member, __thiscall, optional
#define TQ_GFX_CANVAS_RENDERRECT "?RenderRect@GraphicsCanvas@GAME@@QAEXABVRect@2@ABVColor@2@PBVGraphicsShader2@2@ABVName@2@@Z"
#define TQ_GFX_CANVAS_RENDERRECT_MOD "Engine.dll"
#define TQ_GFX_CANVAS_RENDERRECT_CC TQCC_THISCALL
#define TQ_GFX_CANVAS_RENDERRECT_SRET 0
#define TQ_GFX_CANVAS_RENDERRECT_REQ 0

// public: void __thiscall GAME::GraphicsCanvas::RenderRect(class GAME::Rect const &,class GAME::Rect const &,class GAME::GraphicsTexture const *,class GAME::Color const &,class GAME::GraphicsShader2 const *,class GAME::Name const &)
//   member, __thiscall, optional
#define TQ_GFX_CANVAS_RENDERRECT_TEX "?RenderRect@GraphicsCanvas@GAME@@QAEXABVRect@2@0PBVGraphicsTexture@2@ABVColor@2@PBVGraphicsShader2@2@ABVName@2@@Z"
#define TQ_GFX_CANVAS_RENDERRECT_TEX_MOD "Engine.dll"
#define TQ_GFX_CANVAS_RENDERRECT_TEX_CC TQCC_THISCALL
#define TQ_GFX_CANVAS_RENDERRECT_TEX_SRET 0
#define TQ_GFX_CANVAS_RENDERRECT_TEX_REQ 0

// public: int __thiscall GAME::GraphicsTexture::GetWidth(void)const 
//   member, __thiscall, optional
#define TQ_GFX_TEXTURE_GETWIDTH "?GetWidth@GraphicsTexture@GAME@@QBEHXZ"
#define TQ_GFX_TEXTURE_GETWIDTH_MOD "Engine.dll"
#define TQ_GFX_TEXTURE_GETWIDTH_CC TQCC_THISCALL
#define TQ_GFX_TEXTURE_GETWIDTH_SRET 0
#define TQ_GFX_TEXTURE_GETWIDTH_REQ 0

// public: int __thiscall GAME::GraphicsTexture::GetHeight(void)const 
//   member, __thiscall, optional
#define TQ_GFX_TEXTURE_GETHEIGHT "?GetHeight@GraphicsTexture@GAME@@QBEHXZ"
#define TQ_GFX_TEXTURE_GETHEIGHT_MOD "Engine.dll"
#define TQ_GFX_TEXTURE_GETHEIGHT_CC TQCC_THISCALL
#define TQ_GFX_TEXTURE_GETHEIGHT_SRET 0
#define TQ_GFX_TEXTURE_GETHEIGHT_REQ 0

// public: void __thiscall GAME::GraphicsEngine::UnloadTexture(class GAME::GraphicsTexture const *)
//   member, __thiscall, optional
#define TQ_GFX_UNLOADTEXTURE "?UnloadTexture@GraphicsEngine@GAME@@QAEXPBVGraphicsTexture@2@@Z"
#define TQ_GFX_UNLOADTEXTURE_MOD "Engine.dll"
#define TQ_GFX_UNLOADTEXTURE_CC TQCC_THISCALL
#define TQ_GFX_UNLOADTEXTURE_SRET 0
#define TQ_GFX_UNLOADTEXTURE_REQ 0

// public: float __thiscall GAME::GraphicsCanvas::RenderText(int,int,class GAME::Color const &,char const *,class GAME::GraphicsFont const *,int,enum GAME::GraphicsCanvas::XAlignment,enum GAME::GraphicsCanvas::YAlignment,bool,int,enum GAME::RenderFontStyle,bool)
//   member, __thiscall, optional
#define TQ_GFX_CANVAS_RENDERTEXT_A "?RenderText@GraphicsCanvas@GAME@@QAEMHHABVColor@2@PBDPBVGraphicsFont@2@HW4XAlignment@12@W4YAlignment@12@_NHW4RenderFontStyle@2@5@Z"
#define TQ_GFX_CANVAS_RENDERTEXT_A_MOD "Engine.dll"
#define TQ_GFX_CANVAS_RENDERTEXT_A_CC TQCC_THISCALL
#define TQ_GFX_CANVAS_RENDERTEXT_A_SRET 0
#define TQ_GFX_CANVAS_RENDERTEXT_A_REQ 0

// public: float __thiscall GAME::GraphicsCanvas::RenderText(int,int,class GAME::Color const &,unsigned short const *,class GAME::GraphicsFont const *,int,enum GAME::GraphicsCanvas::XAlignment,enum GAME::GraphicsCanvas::YAlignment,bool,int,enum GAME::RenderFontStyle,bool)
//   member, __thiscall, optional
#define TQ_GFX_CANVAS_RENDERTEXT_W "?RenderText@GraphicsCanvas@GAME@@QAEMHHABVColor@2@PBGPBVGraphicsFont@2@HW4XAlignment@12@W4YAlignment@12@_NHW4RenderFontStyle@2@5@Z"
#define TQ_GFX_CANVAS_RENDERTEXT_W_MOD "Engine.dll"
#define TQ_GFX_CANVAS_RENDERTEXT_W_CC TQCC_THISCALL
#define TQ_GFX_CANVAS_RENDERTEXT_W_SRET 0
#define TQ_GFX_CANVAS_RENDERTEXT_W_REQ 0

// public: static enum GAME::RenderApiId __cdecl GAME::RenderDevice::GetActiveAPI(void)
//   static member, __cdecl, optional
#define TQ_GFX_RD_GETACTIVEAPI "?GetActiveAPI@RenderDevice@GAME@@SA?AW4RenderApiId@2@XZ"
#define TQ_GFX_RD_GETACTIVEAPI_MOD "Engine.dll"
#define TQ_GFX_RD_GETACTIVEAPI_CC TQCC_CDECL
#define TQ_GFX_RD_GETACTIVEAPI_SRET 0
#define TQ_GFX_RD_GETACTIVEAPI_REQ 0

// public: class GAME::GraphicsFont const * __thiscall GAME::GraphicsEngine::LoadFont(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool,bool)
//   member, __thiscall, optional
#define TQ_GFX_LOADFONT "?LoadFont@GraphicsEngine@GAME@@QAEPBVGraphicsFont@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N1@Z"
#define TQ_GFX_LOADFONT_MOD "Engine.dll"
#define TQ_GFX_LOADFONT_CC TQCC_THISCALL
#define TQ_GFX_LOADFONT_SRET 0
#define TQ_GFX_LOADFONT_REQ 0

// ---------------------------------------------------------------------------------------------
// Object lookup and records   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: static class GAME::ObjectManager * __cdecl GAME::Singleton<class GAME::ObjectManager>::Get(void)
//   static member, __cdecl, optional
#define TQ_OBJ_OM_GET "?Get@?$Singleton@VObjectManager@GAME@@@GAME@@SAPAVObjectManager@2@XZ"
#define TQ_OBJ_OM_GET_MOD "Engine.dll"
#define TQ_OBJ_OM_GET_CC TQCC_CDECL
#define TQ_OBJ_OM_GET_SRET 0
#define TQ_OBJ_OM_GET_REQ 0

// public: void __thiscall GAME::ObjectManager::DestroyObjectEx(class GAME::Object *,char const *,int)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, optional
#define TQ_OBJ_OM_DESTROYOBJECTEX "?DestroyObjectEx@ObjectManager@GAME@@QAEXPAVObject@2@PBDH@Z"
#define TQ_OBJ_OM_DESTROYOBJECTEX_MOD "Engine.dll"
#define TQ_OBJ_OM_DESTROYOBJECTEX_CC TQCC_THISCALL
#define TQ_OBJ_OM_DESTROYOBJECTEX_SRET 0
#define TQ_OBJ_OM_DESTROYOBJECTEX_REQ 0

// public: unsigned int __thiscall GAME::Object::GetObjectId(void)const 
//   member, __thiscall, optional
#define TQ_OBJ_GETOBJECTID "?GetObjectId@Object@GAME@@QBEIXZ"
#define TQ_OBJ_GETOBJECTID_MOD "Engine.dll"
#define TQ_OBJ_GETOBJECTID_CC TQCC_THISCALL
#define TQ_OBJ_GETOBJECTID_SRET 0
#define TQ_OBJ_GETOBJECTID_REQ 0

// public: char const * __thiscall GAME::Object::GetObjectName(void)const 
//   member, __thiscall, optional
#define TQ_OBJ_GETOBJECTNAME "?GetObjectName@Object@GAME@@QBEPBDXZ"
#define TQ_OBJ_GETOBJECTNAME_MOD "Engine.dll"
#define TQ_OBJ_GETOBJECTNAME_CC TQCC_THISCALL
#define TQ_OBJ_GETOBJECTNAME_SRET 0
#define TQ_OBJ_GETOBJECTNAME_REQ 0

// public: virtual int __thiscall GAME::LoadTableBinary::GetInt(char const *,int)const 
//   virtual member, __thiscall, optional
#define TQ_OBJ_LTB_GETINT "?GetInt@LoadTableBinary@GAME@@UBEHPBDH@Z"
#define TQ_OBJ_LTB_GETINT_MOD "Engine.dll"
#define TQ_OBJ_LTB_GETINT_CC TQCC_THISCALL
#define TQ_OBJ_LTB_GETINT_SRET 0
#define TQ_OBJ_LTB_GETINT_REQ 0

// public: void __thiscall GAME::ObjectManager::GetObjectList(class std::vector<class GAME::Object const *,class std::allocator<class GAME::Object const *> > &)const 
//   member, __thiscall, optional
#define TQ_OBJ_OM_GETOBJECTLIST "?GetObjectList@ObjectManager@GAME@@QBEXAAV?$vector@PBVObject@GAME@@V?$allocator@PBVObject@GAME@@@std@@@std@@@Z"
#define TQ_OBJ_OM_GETOBJECTLIST_MOD "Engine.dll"
#define TQ_OBJ_OM_GETOBJECTLIST_CC TQCC_THISCALL
#define TQ_OBJ_OM_GETOBJECTLIST_SRET 0
#define TQ_OBJ_OM_GETOBJECTLIST_REQ 0

// ---------------------------------------------------------------------------------------------
// GameEngine - the frame, the three stores, the caravan   [Game.dll]
// ---------------------------------------------------------------------------------------------
// class GAME::GameEngine * GAME::gGameEngine
//   global data, data, REQUIRED
#define TQ_GAMEENGINE_GGAMEENGINE "?gGameEngine@GAME@@3PAVGameEngine@1@A"
#define TQ_GAMEENGINE_GGAMEENGINE_MOD "Game.dll"
#define TQ_GAMEENGINE_GGAMEENGINE_CC TQCC_DATA
#define TQ_GAMEENGINE_GGAMEENGINE_SRET 0
#define TQ_GAMEENGINE_GGAMEENGINE_REQ 1

// public: void __thiscall GAME::GameEngine::Update(int)
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_UPDATE "?Update@GameEngine@GAME@@QAEXH@Z"
#define TQ_GAMEENGINE_UPDATE_MOD "Game.dll"
#define TQ_GAMEENGINE_UPDATE_CC TQCC_THISCALL
#define TQ_GAMEENGINE_UPDATE_SRET 0
#define TQ_GAMEENGINE_UPDATE_REQ 1

// public: class GAME::Player * __thiscall GAME::GameEngine::GetMainPlayer(void)const 
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_GETMAINPLAYER "?GetMainPlayer@GameEngine@GAME@@QBEPAVPlayer@2@XZ"
#define TQ_GAMEENGINE_GETMAINPLAYER_MOD "Game.dll"
#define TQ_GAMEENGINE_GETMAINPLAYER_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETMAINPLAYER_SRET 0
#define TQ_GAMEENGINE_GETMAINPLAYER_REQ 1

// public: bool __thiscall GAME::GameEngine::GetItemColor(enum GAME::ItemClassification,class GAME::Color &)const 
//   member, __thiscall, optional
#define TQ_GAMEENGINE_GETITEMCOLOR "?GetItemColor@GameEngine@GAME@@QBE_NW4ItemClassification@2@AAVColor@2@@Z"
#define TQ_GAMEENGINE_GETITEMCOLOR_MOD "Game.dll"
#define TQ_GAMEENGINE_GETITEMCOLOR_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETITEMCOLOR_SRET 0
#define TQ_GAMEENGINE_GETITEMCOLOR_REQ 0

// public: float __thiscall GAME::GameEngine::GetItemBackgroundOpacity(bool)const 
//   member, __thiscall, optional
#define TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY "?GetItemBackgroundOpacity@GameEngine@GAME@@QBEM_N@Z"
#define TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY_MOD "Game.dll"
#define TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY_SRET 0
#define TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY_REQ 0

// public: class GAME::InventorySack & __thiscall GAME::GameEngine::GetPlayerStash(void)
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_GETPLAYERSTASH "?GetPlayerStash@GameEngine@GAME@@QAEAAVInventorySack@2@XZ"
#define TQ_GAMEENGINE_GETPLAYERSTASH_MOD "Game.dll"
#define TQ_GAMEENGINE_GETPLAYERSTASH_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETPLAYERSTASH_SRET 0
#define TQ_GAMEENGINE_GETPLAYERSTASH_REQ 1

// public: class GAME::InventorySack const & __thiscall GAME::GameEngine::GetPlayerStash(void)const 
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_GETPLAYERSTASH_C "?GetPlayerStash@GameEngine@GAME@@QBEABVInventorySack@2@XZ"
#define TQ_GAMEENGINE_GETPLAYERSTASH_C_MOD "Game.dll"
#define TQ_GAMEENGINE_GETPLAYERSTASH_C_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETPLAYERSTASH_C_SRET 0
#define TQ_GAMEENGINE_GETPLAYERSTASH_C_REQ 1

// public: class GAME::InventorySack & __thiscall GAME::GameEngine::GetPlayerTransfer(void)
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_GETPLAYERTRANSFER "?GetPlayerTransfer@GameEngine@GAME@@QAEAAVInventorySack@2@XZ"
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_MOD "Game.dll"
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_SRET 0
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_REQ 1

// public: class GAME::InventorySack const & __thiscall GAME::GameEngine::GetPlayerTransfer(void)const 
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_C "?GetPlayerTransfer@GameEngine@GAME@@QBEABVInventorySack@2@XZ"
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_C_MOD "Game.dll"
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_C_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_C_SRET 0
#define TQ_GAMEENGINE_GETPLAYERTRANSFER_C_REQ 1

// public: class GAME::InventorySack & __thiscall GAME::GameEngine::GetPlayerRelicVault(void)
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT "?GetPlayerRelicVault@GameEngine@GAME@@QAEAAVInventorySack@2@XZ"
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_MOD "Game.dll"
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_SRET 0
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_REQ 1

// public: class GAME::InventorySack const & __thiscall GAME::GameEngine::GetPlayerRelicVault(void)const 
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_C "?GetPlayerRelicVault@GameEngine@GAME@@QBEABVInventorySack@2@XZ"
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_C_MOD "Game.dll"
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_C_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_C_SRET 0
#define TQ_GAMEENGINE_GETPLAYERRELICVAULT_C_REQ 1

// public: int __thiscall GAME::GameEngine::GetCaravanMode(void)const 
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_GETCARAVANMODE "?GetCaravanMode@GameEngine@GAME@@QBEHXZ"
#define TQ_GAMEENGINE_GETCARAVANMODE_MOD "Game.dll"
#define TQ_GAMEENGINE_GETCARAVANMODE_CC TQCC_THISCALL
#define TQ_GAMEENGINE_GETCARAVANMODE_SRET 0
#define TQ_GAMEENGINE_GETCARAVANMODE_REQ 1

// public: void __thiscall GAME::GameEngine::SetCaravanMode(int)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_SETCARAVANMODE "?SetCaravanMode@GameEngine@GAME@@QAEXH@Z"
#define TQ_GAMEENGINE_SETCARAVANMODE_MOD "Game.dll"
#define TQ_GAMEENGINE_SETCARAVANMODE_CC TQCC_THISCALL
#define TQ_GAMEENGINE_SETCARAVANMODE_SRET 0
#define TQ_GAMEENGINE_SETCARAVANMODE_REQ 1

// public: void __thiscall GAME::GameEngine::CaravanGoodbye(void)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_CARAVANGOODBYE "?CaravanGoodbye@GameEngine@GAME@@QAEXXZ"
#define TQ_GAMEENGINE_CARAVANGOODBYE_MOD "Game.dll"
#define TQ_GAMEENGINE_CARAVANGOODBYE_CC TQCC_THISCALL
#define TQ_GAMEENGINE_CARAVANGOODBYE_SRET 0
#define TQ_GAMEENGINE_CARAVANGOODBYE_REQ 1

// public: bool __thiscall GAME::GameEngine::AddItemToStash(unsigned int,bool)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_ADDITEMTOSTASH_ID "?AddItemToStash@GameEngine@GAME@@QAE_NI_N@Z"
#define TQ_GAMEENGINE_ADDITEMTOSTASH_ID_MOD "Game.dll"
#define TQ_GAMEENGINE_ADDITEMTOSTASH_ID_CC TQCC_THISCALL
#define TQ_GAMEENGINE_ADDITEMTOSTASH_ID_SRET 0
#define TQ_GAMEENGINE_ADDITEMTOSTASH_ID_REQ 1

// public: bool __thiscall GAME::GameEngine::AddItemToTransfer(unsigned int,bool)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID "?AddItemToTransfer@GameEngine@GAME@@QAE_NI_N@Z"
#define TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID_MOD "Game.dll"
#define TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID_CC TQCC_THISCALL
#define TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID_SRET 0
#define TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID_REQ 1

// public: bool __thiscall GAME::GameEngine::AdditemToRelicVault(unsigned int,bool)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID "?AdditemToRelicVault@GameEngine@GAME@@QAE_NI_N@Z"
#define TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID_MOD "Game.dll"
#define TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID_CC TQCC_THISCALL
#define TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID_SRET 0
#define TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID_REQ 1

// public: bool __thiscall GAME::GameEngine::RemoveItemFromStash(unsigned int)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_REMOVEITEMFROMSTASH "?RemoveItemFromStash@GameEngine@GAME@@QAE_NI@Z"
#define TQ_GAMEENGINE_REMOVEITEMFROMSTASH_MOD "Game.dll"
#define TQ_GAMEENGINE_REMOVEITEMFROMSTASH_CC TQCC_THISCALL
#define TQ_GAMEENGINE_REMOVEITEMFROMSTASH_SRET 0
#define TQ_GAMEENGINE_REMOVEITEMFROMSTASH_REQ 1

// public: bool __thiscall GAME::GameEngine::RemoveItemFromTransfer(unsigned int)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER "?RemoveItemFromTransfer@GameEngine@GAME@@QAE_NI@Z"
#define TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER_MOD "Game.dll"
#define TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER_CC TQCC_THISCALL
#define TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER_SRET 0
#define TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER_REQ 1

// public: bool __thiscall GAME::GameEngine::RemoveItemFromRelicVault(unsigned int)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, REQUIRED
#define TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT "?RemoveItemFromRelicVault@GameEngine@GAME@@QAE_NI@Z"
#define TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT_MOD "Game.dll"
#define TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT_CC TQCC_THISCALL
#define TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT_SRET 0
#define TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT_REQ 1

// ---------------------------------------------------------------------------------------------
// NpcCaravan / Player   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: virtual void __thiscall GAME::NpcCaravan::OnPlayerInteract(unsigned int,bool,bool)
//   virtual member, __thiscall, REQUIRED
#define TQ_NPC_ONPLAYERINTERACT "?OnPlayerInteract@NpcCaravan@GAME@@UAEXI_N0@Z"
#define TQ_NPC_ONPLAYERINTERACT_MOD "Game.dll"
#define TQ_NPC_ONPLAYERINTERACT_CC TQCC_THISCALL
#define TQ_NPC_ONPLAYERINTERACT_SRET 0
#define TQ_NPC_ONPLAYERINTERACT_REQ 1

// public: bool __thiscall GAME::Player::IsInMainQuest(void)const 
//   member, __thiscall, optional
#define TQ_NPC_PLAYER_ISINMAINQUEST "?IsInMainQuest@Player@GAME@@QBE_NXZ"
#define TQ_NPC_PLAYER_ISINMAINQUEST_MOD "Game.dll"
#define TQ_NPC_PLAYER_ISINMAINQUEST_CC TQCC_THISCALL
#define TQ_NPC_PLAYER_ISINMAINQUEST_SRET 0
#define TQ_NPC_PLAYER_ISINMAINQUEST_REQ 0

// ---------------------------------------------------------------------------------------------
// Character - the owned marking   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: class std::vector<unsigned int,class std::allocator<unsigned int> > const & __thiscall GAME::Character::GetInventoryItems(void)const 
//   member, __thiscall, optional
#define TQ_CHAR_GETINVENTORYITEMS "?GetInventoryItems@Character@GAME@@QBEABV?$vector@IV?$allocator@I@std@@@std@@XZ"
#define TQ_CHAR_GETINVENTORYITEMS_MOD "Game.dll"
#define TQ_CHAR_GETINVENTORYITEMS_CC TQCC_THISCALL
#define TQ_CHAR_GETINVENTORYITEMS_SRET 0
#define TQ_CHAR_GETINVENTORYITEMS_REQ 0

// ---------------------------------------------------------------------------------------------
// Controller - the deposit's disposal   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: unsigned int const __thiscall GAME::Character::GetControllerId(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_GETCONTROLLERID "?GetControllerId@Character@GAME@@QBE?BIXZ"
#define TQ_CTRL_GETCONTROLLERID_MOD "Game.dll"
#define TQ_CTRL_GETCONTROLLERID_CC TQCC_THISCALL
#define TQ_CTRL_GETCONTROLLERID_SRET 0
#define TQ_CTRL_GETCONTROLLERID_REQ 0

// public: void __thiscall GAME::ControllerCharacter::SendRemoveItemFromInventory(unsigned int)
//   member, __thiscall, optional
#define TQ_CTRL_SENDREMOVEITEM "?SendRemoveItemFromInventory@ControllerCharacter@GAME@@QAEXI@Z"
#define TQ_CTRL_SENDREMOVEITEM_MOD "Game.dll"
#define TQ_CTRL_SENDREMOVEITEM_CC TQCC_THISCALL
#define TQ_CTRL_SENDREMOVEITEM_SRET 0
#define TQ_CTRL_SENDREMOVEITEM_REQ 0

// const GAME::ControllerPlayer::`vftable'
//   vftable, data, optional
#define TQ_CTRL_PLAYER_VFTABLE "??_7ControllerPlayer@GAME@@6B@"
#define TQ_CTRL_PLAYER_VFTABLE_MOD "Game.dll"
#define TQ_CTRL_PLAYER_VFTABLE_CC TQCC_DATA
#define TQ_CTRL_PLAYER_VFTABLE_SRET 0
#define TQ_CTRL_PLAYER_VFTABLE_REQ 0

// public: class GAME::PlayerInventoryCtrl & __thiscall GAME::ControllerPlayer::GetInventoryCtrl(void)
//   member, __thiscall, optional
#define TQ_CTRL_PLAYER_GETINVENTORYCTRL "?GetInventoryCtrl@ControllerPlayer@GAME@@QAEAAVPlayerInventoryCtrl@2@XZ"
#define TQ_CTRL_PLAYER_GETINVENTORYCTRL_MOD "Game.dll"
#define TQ_CTRL_PLAYER_GETINVENTORYCTRL_CC TQCC_THISCALL
#define TQ_CTRL_PLAYER_GETINVENTORYCTRL_SRET 0
#define TQ_CTRL_PLAYER_GETINVENTORYCTRL_REQ 0

// public: unsigned int __thiscall GAME::PlayerInventoryCtrl::GetNumberOfSacks(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_INVCTRL_GETNUMBEROFSACKS "?GetNumberOfSacks@PlayerInventoryCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_INVCTRL_GETNUMBEROFSACKS_MOD "Game.dll"
#define TQ_CTRL_INVCTRL_GETNUMBEROFSACKS_CC TQCC_THISCALL
#define TQ_CTRL_INVCTRL_GETNUMBEROFSACKS_SRET 0
#define TQ_CTRL_INVCTRL_GETNUMBEROFSACKS_REQ 0

// public: class GAME::InventorySack * __thiscall GAME::PlayerInventoryCtrl::GetSack(int)
//   member, __thiscall, optional
#define TQ_CTRL_INVCTRL_GETSACK "?GetSack@PlayerInventoryCtrl@GAME@@QAEPAVInventorySack@2@H@Z"
#define TQ_CTRL_INVCTRL_GETSACK_MOD "Game.dll"
#define TQ_CTRL_INVCTRL_GETSACK_CC TQCC_THISCALL
#define TQ_CTRL_INVCTRL_GETSACK_SRET 0
#define TQ_CTRL_INVCTRL_GETSACK_REQ 0

// public: virtual bool __thiscall GAME::Player::IsInventorySpaceAvailable(class GAME::Item const *)const 
//   virtual member, __thiscall, optional
#define TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE "?IsInventorySpaceAvailable@Player@GAME@@UBE_NPBVItem@2@@Z"
#define TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE_MOD "Game.dll"
#define TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE_CC TQCC_THISCALL
#define TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE_SRET 0
#define TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE_REQ 0

// public: void __thiscall GAME::Player::PlayInventoryFullSound(void)
//   member, __thiscall, optional
#define TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND "?PlayInventoryFullSound@Player@GAME@@QAEXXZ"
#define TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND_MOD "Game.dll"
#define TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND_CC TQCC_THISCALL
#define TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND_SRET 0
#define TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND_REQ 0

// public: class GAME::EquipmentCtrl & __thiscall GAME::ControllerCharacter::GetEquipmentCtrl(void)
//   member, __thiscall, optional
#define TQ_CTRL_CHAR_GETEQUIPMENTCTRL "?GetEquipmentCtrl@ControllerCharacter@GAME@@QAEAAVEquipmentCtrl@2@XZ"
#define TQ_CTRL_CHAR_GETEQUIPMENTCTRL_MOD "Game.dll"
#define TQ_CTRL_CHAR_GETEQUIPMENTCTRL_CC TQCC_THISCALL
#define TQ_CTRL_CHAR_GETEQUIPMENTCTRL_SRET 0
#define TQ_CTRL_CHAR_GETEQUIPMENTCTRL_REQ 0

// public: bool __thiscall GAME::EquipmentCtrl::AreRequirementsMet(class GAME::Item *)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET "?AreRequirementsMet@EquipmentCtrl@GAME@@QBE_NPAVItem@2@@Z"
#define TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET_SRET 0
#define TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_Head(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_HEAD "?GetItem_Head@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_HEAD_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_HEAD_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_HEAD_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_HEAD_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_Neck(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_NECK "?GetItem_Neck@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_NECK_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_NECK_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_NECK_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_NECK_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_Artifact(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT "?GetItem_Artifact@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_UpperBody(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY "?GetItem_UpperBody@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_LowerBody(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY "?GetItem_LowerBody@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_Finger1(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1 "?GetItem_Finger1@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_Finger2(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2 "?GetItem_Finger2@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_Forearm(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM "?GetItem_Forearm@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_HandLeft(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT "?GetItem_HandLeft@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT_REQ 0

// public: unsigned int __thiscall GAME::EquipmentCtrl::GetItem_HandRight(void)const 
//   member, __thiscall, optional
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT "?GetItem_HandRight@EquipmentCtrl@GAME@@QBEIXZ"
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT_MOD "Game.dll"
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT_CC TQCC_THISCALL
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT_SRET 0
#define TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT_REQ 0

// ---------------------------------------------------------------------------------------------
// CursorHandlerItemMove - the drop gate   [Game.dll]
// ---------------------------------------------------------------------------------------------
// const GAME::CursorHandlerItemMove::`vftable'
//   vftable, data, REQUIRED
#define TQ_CURSOR_VFTABLE "??_7CursorHandlerItemMove@GAME@@6B@"
#define TQ_CURSOR_VFTABLE_MOD "Game.dll"
#define TQ_CURSOR_VFTABLE_CC TQCC_DATA
#define TQ_CURSOR_VFTABLE_SRET 0
#define TQ_CURSOR_VFTABLE_REQ 1

// public: virtual unsigned int __thiscall GAME::CursorHandlerItemMove::GetId(void)
//   virtual member, __thiscall, REQUIRED
#define TQ_CURSOR_GETID "?GetId@CursorHandlerItemMove@GAME@@UAEIXZ"
#define TQ_CURSOR_GETID_MOD "Game.dll"
#define TQ_CURSOR_GETID_CC TQCC_THISCALL
#define TQ_CURSOR_GETID_SRET 0
#define TQ_CURSOR_GETID_REQ 1

// public: virtual void __thiscall GAME::CursorHandlerItemMove::SetId(unsigned int)  ** WRITE - hooked to observe, never called **
//   virtual member, __thiscall, REQUIRED
#define TQ_CURSOR_SETID "?SetId@CursorHandlerItemMove@GAME@@UAEXI@Z"
#define TQ_CURSOR_SETID_MOD "Game.dll"
#define TQ_CURSOR_SETID_CC TQCC_THISCALL
#define TQ_CURSOR_SETID_SRET 0
#define TQ_CURSOR_SETID_REQ 1

// public: virtual bool __thiscall GAME::CursorHandlerItemMove::PrimaryStashActivate(class GAME::Vec2 const &)
//   virtual member, __thiscall, REQUIRED
#define TQ_CURSOR_PRIMARYSTASHACTIVATE "?PrimaryStashActivate@CursorHandlerItemMove@GAME@@UAE_NABVVec2@2@@Z"
#define TQ_CURSOR_PRIMARYSTASHACTIVATE_MOD "Game.dll"
#define TQ_CURSOR_PRIMARYSTASHACTIVATE_CC TQCC_THISCALL
#define TQ_CURSOR_PRIMARYSTASHACTIVATE_SRET 0
#define TQ_CURSOR_PRIMARYSTASHACTIVATE_REQ 1

// public: virtual bool __thiscall GAME::CursorHandlerItemMove::PrimaryTransferActivate(class GAME::Vec2 const &)
//   virtual member, __thiscall, REQUIRED
#define TQ_CURSOR_PRIMARYTRANSFERACTIVATE "?PrimaryTransferActivate@CursorHandlerItemMove@GAME@@UAE_NABVVec2@2@@Z"
#define TQ_CURSOR_PRIMARYTRANSFERACTIVATE_MOD "Game.dll"
#define TQ_CURSOR_PRIMARYTRANSFERACTIVATE_CC TQCC_THISCALL
#define TQ_CURSOR_PRIMARYTRANSFERACTIVATE_SRET 0
#define TQ_CURSOR_PRIMARYTRANSFERACTIVATE_REQ 1

// public: virtual bool __thiscall GAME::CursorHandlerItemMove::PrimaryRelicVaultActive(class GAME::Vec2 const &)
//   virtual member, __thiscall, REQUIRED
#define TQ_CURSOR_PRIMARYRELICVAULTACTIVE "?PrimaryRelicVaultActive@CursorHandlerItemMove@GAME@@UAE_NABVVec2@2@@Z"
#define TQ_CURSOR_PRIMARYRELICVAULTACTIVE_MOD "Game.dll"
#define TQ_CURSOR_PRIMARYRELICVAULTACTIVE_CC TQCC_THISCALL
#define TQ_CURSOR_PRIMARYRELICVAULTACTIVE_SRET 0
#define TQ_CURSOR_PRIMARYRELICVAULTACTIVE_REQ 1

// public: virtual bool __thiscall GAME::CursorHandlerItemMove::IsStashCapable(void)const 
//   virtual member, __thiscall, optional
#define TQ_CURSOR_ISSTASHCAPABLE "?IsStashCapable@CursorHandlerItemMove@GAME@@UBE_NXZ"
#define TQ_CURSOR_ISSTASHCAPABLE_MOD "Game.dll"
#define TQ_CURSOR_ISSTASHCAPABLE_CC TQCC_THISCALL
#define TQ_CURSOR_ISSTASHCAPABLE_SRET 0
#define TQ_CURSOR_ISSTASHCAPABLE_REQ 0

// public: virtual bool __thiscall GAME::CursorHandlerItemMove::IsTransferCapable(void)const 
//   virtual member, __thiscall, optional
#define TQ_CURSOR_ISTRANSFERCAPABLE "?IsTransferCapable@CursorHandlerItemMove@GAME@@UBE_NXZ"
#define TQ_CURSOR_ISTRANSFERCAPABLE_MOD "Game.dll"
#define TQ_CURSOR_ISTRANSFERCAPABLE_CC TQCC_THISCALL
#define TQ_CURSOR_ISTRANSFERCAPABLE_SRET 0
#define TQ_CURSOR_ISTRANSFERCAPABLE_REQ 0

// public: virtual bool __thiscall GAME::CursorHandlerItemMove::IsRelicVaultCapable(void)const 
//   virtual member, __thiscall, optional
#define TQ_CURSOR_ISRELICVAULTCAPABLE "?IsRelicVaultCapable@CursorHandlerItemMove@GAME@@UBE_NXZ"
#define TQ_CURSOR_ISRELICVAULTCAPABLE_MOD "Game.dll"
#define TQ_CURSOR_ISRELICVAULTCAPABLE_CC TQCC_THISCALL
#define TQ_CURSOR_ISRELICVAULTCAPABLE_SRET 0
#define TQ_CURSOR_ISRELICVAULTCAPABLE_REQ 0

// ---------------------------------------------------------------------------------------------
// InventorySack   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: bool __thiscall GAME::InventorySack::AddItem(class GAME::Item *,bool)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, optional
#define TQ_SACK_ADDITEM "?AddItem@InventorySack@GAME@@QAE_NPAVItem@2@_N@Z"
#define TQ_SACK_ADDITEM_MOD "Game.dll"
#define TQ_SACK_ADDITEM_CC TQCC_THISCALL
#define TQ_SACK_ADDITEM_SRET 0
#define TQ_SACK_ADDITEM_REQ 0

// public: bool __thiscall GAME::InventorySack::AddItem(class GAME::Vec2 const &,class GAME::Item *,bool)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, optional
#define TQ_SACK_ADDITEM_VEC "?AddItem@InventorySack@GAME@@QAE_NABVVec2@2@PAVItem@2@_N@Z"
#define TQ_SACK_ADDITEM_VEC_MOD "Game.dll"
#define TQ_SACK_ADDITEM_VEC_CC TQCC_THISCALL
#define TQ_SACK_ADDITEM_VEC_SRET 0
#define TQ_SACK_ADDITEM_VEC_REQ 0

// public: bool __thiscall GAME::InventorySack::RemoveItem(unsigned int)  ** WRITE - hooked to observe, never called **
//   member, __thiscall, optional
#define TQ_SACK_REMOVEITEM "?RemoveItem@InventorySack@GAME@@QAE_NI@Z"
#define TQ_SACK_REMOVEITEM_MOD "Game.dll"
#define TQ_SACK_REMOVEITEM_CC TQCC_THISCALL
#define TQ_SACK_REMOVEITEM_SRET 0
#define TQ_SACK_REMOVEITEM_REQ 0

// public: bool __thiscall GAME::InventorySack::IsSpaceForItem(class GAME::Item const *)const 
//   member, __thiscall, optional
#define TQ_SACK_ISSPACEFORITEM "?IsSpaceForItem@InventorySack@GAME@@QBE_NPBVItem@2@@Z"
#define TQ_SACK_ISSPACEFORITEM_MOD "Game.dll"
#define TQ_SACK_ISSPACEFORITEM_CC TQCC_THISCALL
#define TQ_SACK_ISSPACEFORITEM_SRET 0
#define TQ_SACK_ISSPACEFORITEM_REQ 0

// public: unsigned int __thiscall GAME::InventorySack::GetItemUnderPoint(class GAME::Vec2)const 
//   member, __thiscall, optional
#define TQ_SACK_GETITEMUNDERPOINT "?GetItemUnderPoint@InventorySack@GAME@@QBEIVVec2@2@@Z"
#define TQ_SACK_GETITEMUNDERPOINT_MOD "Game.dll"
#define TQ_SACK_GETITEMUNDERPOINT_CC TQCC_THISCALL
#define TQ_SACK_GETITEMUNDERPOINT_SRET 0
#define TQ_SACK_GETITEMUNDERPOINT_REQ 0

// public: __thiscall GAME::InventorySack::InventorySack(void)
//   member, __thiscall, optional
#define TQ_SACK_CTOR "??0InventorySack@GAME@@QAE@XZ"
#define TQ_SACK_CTOR_MOD "Game.dll"
#define TQ_SACK_CTOR_CC TQCC_THISCALL
#define TQ_SACK_CTOR_SRET 0
#define TQ_SACK_CTOR_REQ 0

// const GAME::InventorySack::`vftable'
//   vftable, data, optional
#define TQ_SACK_VFTABLE "??_7InventorySack@GAME@@6B@"
#define TQ_SACK_VFTABLE_MOD "Game.dll"
#define TQ_SACK_VFTABLE_CC TQCC_DATA
#define TQ_SACK_VFTABLE_SRET 0
#define TQ_SACK_VFTABLE_REQ 0

// public: bool __thiscall GAME::InventorySack::Sort(unsigned int)
//   member, __thiscall, optional
#define TQ_SACK_SORT "?Sort@InventorySack@GAME@@QAE_NI@Z"
#define TQ_SACK_SORT_MOD "Game.dll"
#define TQ_SACK_SORT_CC TQCC_THISCALL
#define TQ_SACK_SORT_SRET 0
#define TQ_SACK_SORT_REQ 0

// public: void __thiscall GAME::InventorySack::SetDims(int,int,bool)
//   member, __thiscall, optional
#define TQ_SACK_SETDIMS "?SetDims@InventorySack@GAME@@QAEXHH_N@Z"
#define TQ_SACK_SETDIMS_MOD "Game.dll"
#define TQ_SACK_SETDIMS_CC TQCC_THISCALL
#define TQ_SACK_SETDIMS_SRET 0
#define TQ_SACK_SETDIMS_REQ 0

// public: bool __thiscall GAME::InventorySack::ContainsItem(unsigned int)const 
//   member, __thiscall, optional
#define TQ_SACK_CONTAINSITEM "?ContainsItem@InventorySack@GAME@@QBE_NI@Z"
#define TQ_SACK_CONTAINSITEM_MOD "Game.dll"
#define TQ_SACK_CONTAINSITEM_CC TQCC_THISCALL
#define TQ_SACK_CONTAINSITEM_SRET 0
#define TQ_SACK_CONTAINSITEM_REQ 0

// public: unsigned int __thiscall GAME::InventorySack::GetCellWidth(void)const 
//   member, __thiscall, optional
#define TQ_SACK_GETCELLWIDTH "?GetCellWidth@InventorySack@GAME@@QBEIXZ"
#define TQ_SACK_GETCELLWIDTH_MOD "Game.dll"
#define TQ_SACK_GETCELLWIDTH_CC TQCC_THISCALL
#define TQ_SACK_GETCELLWIDTH_SRET 0
#define TQ_SACK_GETCELLWIDTH_REQ 0

// public: unsigned int __thiscall GAME::InventorySack::GetCellHeight(void)const 
//   member, __thiscall, optional
#define TQ_SACK_GETCELLHEIGHT "?GetCellHeight@InventorySack@GAME@@QBEIXZ"
#define TQ_SACK_GETCELLHEIGHT_MOD "Game.dll"
#define TQ_SACK_GETCELLHEIGHT_CC TQCC_THISCALL
#define TQ_SACK_GETCELLHEIGHT_SRET 0
#define TQ_SACK_GETCELLHEIGHT_REQ 0

// public: unsigned int __thiscall GAME::InventorySack::GetGridWidth(void)const 
//   member, __thiscall, optional
#define TQ_SACK_GETGRIDWIDTH "?GetGridWidth@InventorySack@GAME@@QBEIXZ"
#define TQ_SACK_GETGRIDWIDTH_MOD "Game.dll"
#define TQ_SACK_GETGRIDWIDTH_CC TQCC_THISCALL
#define TQ_SACK_GETGRIDWIDTH_SRET 0
#define TQ_SACK_GETGRIDWIDTH_REQ 0

// public: unsigned int __thiscall GAME::InventorySack::GetGridHeight(void)const 
//   member, __thiscall, optional
#define TQ_SACK_GETGRIDHEIGHT "?GetGridHeight@InventorySack@GAME@@QBEIXZ"
#define TQ_SACK_GETGRIDHEIGHT_MOD "Game.dll"
#define TQ_SACK_GETGRIDHEIGHT_CC TQCC_THISCALL
#define TQ_SACK_GETGRIDHEIGHT_SRET 0
#define TQ_SACK_GETGRIDHEIGHT_REQ 0

// public: class std::map<unsigned int,struct GAME::RectExt,struct std::less<unsigned int>,class std::allocator<struct std::pair<unsigned int const ,struct GAME::RectExt> > > const & __thiscall GAME::InventorySack::GetInventory(void)const 
//   member, __thiscall, optional
#define TQ_SACK_GETINVENTORY "?GetInventory@InventorySack@GAME@@QBEABV?$map@IURectExt@GAME@@U?$less@I@std@@V?$allocator@U?$pair@$$CBIURectExt@GAME@@@std@@@4@@std@@XZ"
#define TQ_SACK_GETINVENTORY_MOD "Game.dll"
#define TQ_SACK_GETINVENTORY_CC TQCC_THISCALL
#define TQ_SACK_GETINVENTORY_SRET 0
#define TQ_SACK_GETINVENTORY_REQ 0

// ---------------------------------------------------------------------------------------------
// Item   [Game.dll]
// ---------------------------------------------------------------------------------------------
// const GAME::Item::`vftable'{for `GAME::Actor'}
//   vftable, data, optional
#define TQ_ITEM_VFTABLE "??_7Item@GAME@@6BActor@1@@"
#define TQ_ITEM_VFTABLE_MOD "Game.dll"
#define TQ_ITEM_VFTABLE_CC TQCC_DATA
#define TQ_ITEM_VFTABLE_SRET 0
#define TQ_ITEM_VFTABLE_REQ 0

// public: static class GAME::Item * __cdecl GAME::Item::CreateItem(struct GAME::ItemReplicaInfo const &)  ** WRITE - hooked to observe, never called **
//   static member, __cdecl, optional
#define TQ_ITEM_CREATEITEM "?CreateItem@Item@GAME@@SAPAV12@ABUItemReplicaInfo@2@@Z"
#define TQ_ITEM_CREATEITEM_MOD "Game.dll"
#define TQ_ITEM_CREATEITEM_CC TQCC_CDECL
#define TQ_ITEM_CREATEITEM_SRET 0
#define TQ_ITEM_CREATEITEM_REQ 0

// public: virtual void __thiscall GAME::Item::GetItemReplicaInfo(struct GAME::ItemReplicaInfo &)const 
//   virtual member, __thiscall, optional
#define TQ_ITEM_GETITEMREPLICAINFO "?GetItemReplicaInfo@Item@GAME@@UBEXAAUItemReplicaInfo@2@@Z"
#define TQ_ITEM_GETITEMREPLICAINFO_MOD "Game.dll"
#define TQ_ITEM_GETITEMREPLICAINFO_CC TQCC_THISCALL
#define TQ_ITEM_GETITEMREPLICAINFO_SRET 0
#define TQ_ITEM_GETITEMREPLICAINFO_REQ 0

// public: virtual enum GAME::ItemClassification __thiscall GAME::Item::GetItemClassification(void)const 
//   virtual member, __thiscall, optional
#define TQ_ITEM_GETITEMCLASSIFICATION "?GetItemClassification@Item@GAME@@UBE?AW4ItemClassification@2@XZ"
#define TQ_ITEM_GETITEMCLASSIFICATION_MOD "Game.dll"
#define TQ_ITEM_GETITEMCLASSIFICATION_CC TQCC_THISCALL
#define TQ_ITEM_GETITEMCLASSIFICATION_SRET 0
#define TQ_ITEM_GETITEMCLASSIFICATION_REQ 0

// public: virtual enum GAME::Item_Type const __thiscall GAME::Item::GetItemType(void)const 
//   virtual member, __thiscall, optional
#define TQ_ITEM_GETITEMTYPE "?GetItemType@Item@GAME@@UBE?BW4Item_Type@2@XZ"
#define TQ_ITEM_GETITEMTYPE_MOD "Game.dll"
#define TQ_ITEM_GETITEMTYPE_CC TQCC_THISCALL
#define TQ_ITEM_GETITEMTYPE_SRET 0
#define TQ_ITEM_GETITEMTYPE_REQ 0

// public: enum GAME::ItemClassification __thiscall GAME::Item::GetActualItemClassification(void)const 
//   member, __thiscall, optional
#define TQ_ITEM_GETACTUALITEMCLASSIFICATION "?GetActualItemClassification@Item@GAME@@QBE?AW4ItemClassification@2@XZ"
#define TQ_ITEM_GETACTUALITEMCLASSIFICATION_MOD "Game.dll"
#define TQ_ITEM_GETACTUALITEMCLASSIFICATION_CC TQCC_THISCALL
#define TQ_ITEM_GETACTUALITEMCLASSIFICATION_SRET 0
#define TQ_ITEM_GETACTUALITEMCLASSIFICATION_REQ 0

// public: virtual unsigned int __thiscall GAME::Item::GetNumberInStack(void)const 
//   virtual member, __thiscall, optional
#define TQ_ITEM_GETNUMBERINSTACK "?GetNumberInStack@Item@GAME@@UBEIXZ"
#define TQ_ITEM_GETNUMBERINSTACK_MOD "Game.dll"
#define TQ_ITEM_GETNUMBERINSTACK_CC TQCC_THISCALL
#define TQ_ITEM_GETNUMBERINSTACK_SRET 0
#define TQ_ITEM_GETNUMBERINSTACK_REQ 0

// ---------------------------------------------------------------------------------------------
// Item rollover - the collection tooltip line   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: virtual void __thiscall GAME::Item::GetUIDisplayText(class GAME::Character const *,class std::vector<struct GAME::GameTextLine,class std::allocator<struct GAME::GameTextLine> > &)const 
//   virtual member, __thiscall, optional
#define TQ_TIP_ITEM_GETUIDISPLAYTEXT "?GetUIDisplayText@Item@GAME@@UBEXPBVCharacter@2@AAV?$vector@UGameTextLine@GAME@@V?$allocator@UGameTextLine@GAME@@@std@@@std@@@Z"
#define TQ_TIP_ITEM_GETUIDISPLAYTEXT_MOD "Game.dll"
#define TQ_TIP_ITEM_GETUIDISPLAYTEXT_CC TQCC_THISCALL
#define TQ_TIP_ITEM_GETUIDISPLAYTEXT_SRET 0
#define TQ_TIP_ITEM_GETUIDISPLAYTEXT_REQ 0

// public: virtual void __thiscall GAME::ItemEquipment::GetUIDisplayText(class GAME::Character const *,class std::vector<struct GAME::GameTextLine,class std::allocator<struct GAME::GameTextLine> > &)const 
//   virtual member, __thiscall, optional
#define TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT "?GetUIDisplayText@ItemEquipment@GAME@@UBEXPBVCharacter@2@AAV?$vector@UGameTextLine@GAME@@V?$allocator@UGameTextLine@GAME@@@std@@@std@@@Z"
#define TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT_MOD "Game.dll"
#define TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT_CC TQCC_THISCALL
#define TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT_SRET 0
#define TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT_REQ 0

// public: virtual void __thiscall GAME::ItemArtifact::GetUIDisplayText(class GAME::Character const *,class std::vector<struct GAME::GameTextLine,class std::allocator<struct GAME::GameTextLine> > &)const 
//   virtual member, __thiscall, optional
#define TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT "?GetUIDisplayText@ItemArtifact@GAME@@UBEXPBVCharacter@2@AAV?$vector@UGameTextLine@GAME@@V?$allocator@UGameTextLine@GAME@@@std@@@std@@@Z"
#define TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT_MOD "Game.dll"
#define TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT_CC TQCC_THISCALL
#define TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT_SRET 0
#define TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT_REQ 0

// public: virtual void __thiscall GAME::ItemRelic::GetUIDisplayText(class GAME::Character const *,class std::vector<struct GAME::GameTextLine,class std::allocator<struct GAME::GameTextLine> > &)const 
//   virtual member, __thiscall, optional
#define TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT "?GetUIDisplayText@ItemRelic@GAME@@UBEXPBVCharacter@2@AAV?$vector@UGameTextLine@GAME@@V?$allocator@UGameTextLine@GAME@@@std@@@std@@@Z"
#define TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT_MOD "Game.dll"
#define TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT_CC TQCC_THISCALL
#define TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT_SRET 0
#define TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT_REQ 0

// void __cdecl GAME::GameTextLineToString(class std::vector<struct GAME::GameTextLine,class std::allocator<struct GAME::GameTextLine> > const &,class std::list<struct GAME::GameTextString,class std::allocator<struct GAME::GameTextString> > &)
//   free function, __cdecl, optional
#define TQ_TIP_GAMETEXTLINETOSTRING "?GameTextLineToString@GAME@@YAXABV?$vector@UGameTextLine@GAME@@V?$allocator@UGameTextLine@GAME@@@std@@@std@@AAV?$list@UGameTextString@GAME@@V?$allocator@UGameTextString@GAME@@@std@@@3@@Z"
#define TQ_TIP_GAMETEXTLINETOSTRING_MOD "Game.dll"
#define TQ_TIP_GAMETEXTLINETOSTRING_CC TQCC_CDECL
#define TQ_TIP_GAMETEXTLINETOSTRING_SRET 0
#define TQ_TIP_GAMETEXTLINETOSTRING_REQ 0

// public: __thiscall GAME::GameTextLine::GameTextLine(enum GAME::GameTextClass,class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > const &,bool)
//   member, __thiscall, optional
#define TQ_TIP_GAMETEXTLINE_CTOR "??0GameTextLine@GAME@@QAE@W4GameTextClass@1@ABV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@_N@Z"
#define TQ_TIP_GAMETEXTLINE_CTOR_MOD "Game.dll"
#define TQ_TIP_GAMETEXTLINE_CTOR_CC TQCC_THISCALL
#define TQ_TIP_GAMETEXTLINE_CTOR_SRET 0
#define TQ_TIP_GAMETEXTLINE_CTOR_REQ 0

// ---------------------------------------------------------------------------------------------
// MSVCR110 - the game's C runtime   [MSVCR110.dll]
// ---------------------------------------------------------------------------------------------
// void __cdecl operator delete(void *)
//   free function, __cdecl, optional
#define TQ_CRT_OPERATORDELETE "??3@YAXPAX@Z"
#define TQ_CRT_OPERATORDELETE_MOD "MSVCR110.dll"
#define TQ_CRT_OPERATORDELETE_CC TQCC_CDECL
#define TQ_CRT_OPERATORDELETE_SRET 0
#define TQ_CRT_OPERATORDELETE_REQ 0

// Every row, for the offline test: X(macro, module, decorated name, required)
#define TQ_EXPORTS_FOR_EACH(X) \
    X(TQ_ENGINE_GENGINE, TQ_ENGINE_GENGINE_MOD, TQ_ENGINE_GENGINE, TQ_ENGINE_GENGINE_REQ) \
    X(TQ_ENGINE_PRESENTSURFACE, TQ_ENGINE_PRESENTSURFACE_MOD, TQ_ENGINE_PRESENTSURFACE, TQ_ENGINE_PRESENTSURFACE_REQ) \
    X(TQ_ENGINE_LOADMAINDATABASE, TQ_ENGINE_LOADMAINDATABASE_MOD, TQ_ENGINE_LOADMAINDATABASE, TQ_ENGINE_LOADMAINDATABASE_REQ) \
    X(TQ_ENGINE_LOADDATABASE, TQ_ENGINE_LOADDATABASE_MOD, TQ_ENGINE_LOADDATABASE, TQ_ENGINE_LOADDATABASE_REQ) \
    X(TQ_ENGINE_GETDATABASEARCHIVECHECKSUM, TQ_ENGINE_GETDATABASEARCHIVECHECKSUM_MOD, TQ_ENGINE_GETDATABASEARCHIVECHECKSUM, TQ_ENGINE_GETDATABASEARCHIVECHECKSUM_REQ) \
    X(TQ_ENGINE_HASLOADEDCUSTOMDATABASE, TQ_ENGINE_HASLOADEDCUSTOMDATABASE_MOD, TQ_ENGINE_HASLOADEDCUSTOMDATABASE, TQ_ENGINE_HASLOADEDCUSTOMDATABASE_REQ) \
    X(TQ_ENGINE_INITIALIZEMOD, TQ_ENGINE_INITIALIZEMOD_MOD, TQ_ENGINE_INITIALIZEMOD, TQ_ENGINE_INITIALIZEMOD_REQ) \
    X(TQ_ENGINE_GETGAMEINFO, TQ_ENGINE_GETGAMEINFO_MOD, TQ_ENGINE_GETGAMEINFO, TQ_ENGINE_GETGAMEINFO_REQ) \
    X(TQ_ENGINE_ISNETWORKCLIENT, TQ_ENGINE_ISNETWORKCLIENT_MOD, TQ_ENGINE_ISNETWORKCLIENT, TQ_ENGINE_ISNETWORKCLIENT_REQ) \
    X(TQ_ENGINE_ISNETWORKSERVER, TQ_ENGINE_ISNETWORKSERVER_MOD, TQ_ENGINE_ISNETWORKSERVER, TQ_ENGINE_ISNETWORKSERVER_REQ) \
    X(TQ_ENGINE_GETGRAPHICSENGINE, TQ_ENGINE_GETGRAPHICSENGINE_MOD, TQ_ENGINE_GETGRAPHICSENGINE, TQ_ENGINE_GETGRAPHICSENGINE_REQ) \
    X(TQ_ENGINE_GETFILESYSTEM, TQ_ENGINE_GETFILESYSTEM_MOD, TQ_ENGINE_GETFILESYSTEM, TQ_ENGINE_GETFILESYSTEM_REQ) \
    X(TQ_ENGINE_FS_ADDSOURCE, TQ_ENGINE_FS_ADDSOURCE_MOD, TQ_ENGINE_FS_ADDSOURCE, TQ_ENGINE_FS_ADDSOURCE_REQ) \
    X(TQ_ENGINE_GETUISCALE, TQ_ENGINE_GETUISCALE_MOD, TQ_ENGINE_GETUISCALE, TQ_ENGINE_GETUISCALE_REQ) \
    X(TQ_ENGINE_GETOPTIONS, TQ_ENGINE_GETOPTIONS_MOD, TQ_ENGINE_GETOPTIONS, TQ_ENGINE_GETOPTIONS_REQ) \
    X(TQ_ENGINE_OPTIONS_GETBOOL, TQ_ENGINE_OPTIONS_GETBOOL_MOD, TQ_ENGINE_OPTIONS_GETBOOL, TQ_ENGINE_OPTIONS_GETBOOL_REQ) \
    X(TQ_INPUT_DISPLAY_HANDLEKEYEVENT, TQ_INPUT_DISPLAY_HANDLEKEYEVENT_MOD, TQ_INPUT_DISPLAY_HANDLEKEYEVENT, TQ_INPUT_DISPLAY_HANDLEKEYEVENT_REQ) \
    X(TQ_INPUT_BUTTONEVENT_GETTEXT, TQ_INPUT_BUTTONEVENT_GETTEXT_MOD, TQ_INPUT_BUTTONEVENT_GETTEXT, TQ_INPUT_BUTTONEVENT_GETTEXT_REQ) \
    X(TQ_GAMEINFO_GETISMULTIPLAYER, TQ_GAMEINFO_GETISMULTIPLAYER_MOD, TQ_GAMEINFO_GETISMULTIPLAYER, TQ_GAMEINFO_GETISMULTIPLAYER_REQ) \
    X(TQ_GAMEINFO_GETMODNAME, TQ_GAMEINFO_GETMODNAME_MOD, TQ_GAMEINFO_GETMODNAME, TQ_GAMEINFO_GETMODNAME_REQ) \
    X(TQ_GFX_GETCANVAS, TQ_GFX_GETCANVAS_MOD, TQ_GFX_GETCANVAS, TQ_GFX_GETCANVAS_REQ) \
    X(TQ_GFX_ISDOWNSIZING, TQ_GFX_ISDOWNSIZING_MOD, TQ_GFX_ISDOWNSIZING, TQ_GFX_ISDOWNSIZING_REQ) \
    X(TQ_GFX_LOADTEXTURE, TQ_GFX_LOADTEXTURE_MOD, TQ_GFX_LOADTEXTURE, TQ_GFX_LOADTEXTURE_REQ) \
    X(TQ_GFX_CANVAS_GETWIDTH, TQ_GFX_CANVAS_GETWIDTH_MOD, TQ_GFX_CANVAS_GETWIDTH, TQ_GFX_CANVAS_GETWIDTH_REQ) \
    X(TQ_GFX_CANVAS_GETHEIGHT, TQ_GFX_CANVAS_GETHEIGHT_MOD, TQ_GFX_CANVAS_GETHEIGHT, TQ_GFX_CANVAS_GETHEIGHT_REQ) \
    X(TQ_GFX_CANVAS_RENDERRECT, TQ_GFX_CANVAS_RENDERRECT_MOD, TQ_GFX_CANVAS_RENDERRECT, TQ_GFX_CANVAS_RENDERRECT_REQ) \
    X(TQ_GFX_CANVAS_RENDERRECT_TEX, TQ_GFX_CANVAS_RENDERRECT_TEX_MOD, TQ_GFX_CANVAS_RENDERRECT_TEX, TQ_GFX_CANVAS_RENDERRECT_TEX_REQ) \
    X(TQ_GFX_TEXTURE_GETWIDTH, TQ_GFX_TEXTURE_GETWIDTH_MOD, TQ_GFX_TEXTURE_GETWIDTH, TQ_GFX_TEXTURE_GETWIDTH_REQ) \
    X(TQ_GFX_TEXTURE_GETHEIGHT, TQ_GFX_TEXTURE_GETHEIGHT_MOD, TQ_GFX_TEXTURE_GETHEIGHT, TQ_GFX_TEXTURE_GETHEIGHT_REQ) \
    X(TQ_GFX_UNLOADTEXTURE, TQ_GFX_UNLOADTEXTURE_MOD, TQ_GFX_UNLOADTEXTURE, TQ_GFX_UNLOADTEXTURE_REQ) \
    X(TQ_GFX_CANVAS_RENDERTEXT_A, TQ_GFX_CANVAS_RENDERTEXT_A_MOD, TQ_GFX_CANVAS_RENDERTEXT_A, TQ_GFX_CANVAS_RENDERTEXT_A_REQ) \
    X(TQ_GFX_CANVAS_RENDERTEXT_W, TQ_GFX_CANVAS_RENDERTEXT_W_MOD, TQ_GFX_CANVAS_RENDERTEXT_W, TQ_GFX_CANVAS_RENDERTEXT_W_REQ) \
    X(TQ_GFX_RD_GETACTIVEAPI, TQ_GFX_RD_GETACTIVEAPI_MOD, TQ_GFX_RD_GETACTIVEAPI, TQ_GFX_RD_GETACTIVEAPI_REQ) \
    X(TQ_GFX_LOADFONT, TQ_GFX_LOADFONT_MOD, TQ_GFX_LOADFONT, TQ_GFX_LOADFONT_REQ) \
    X(TQ_OBJ_OM_GET, TQ_OBJ_OM_GET_MOD, TQ_OBJ_OM_GET, TQ_OBJ_OM_GET_REQ) \
    X(TQ_OBJ_OM_DESTROYOBJECTEX, TQ_OBJ_OM_DESTROYOBJECTEX_MOD, TQ_OBJ_OM_DESTROYOBJECTEX, TQ_OBJ_OM_DESTROYOBJECTEX_REQ) \
    X(TQ_OBJ_GETOBJECTID, TQ_OBJ_GETOBJECTID_MOD, TQ_OBJ_GETOBJECTID, TQ_OBJ_GETOBJECTID_REQ) \
    X(TQ_OBJ_GETOBJECTNAME, TQ_OBJ_GETOBJECTNAME_MOD, TQ_OBJ_GETOBJECTNAME, TQ_OBJ_GETOBJECTNAME_REQ) \
    X(TQ_OBJ_LTB_GETINT, TQ_OBJ_LTB_GETINT_MOD, TQ_OBJ_LTB_GETINT, TQ_OBJ_LTB_GETINT_REQ) \
    X(TQ_OBJ_OM_GETOBJECTLIST, TQ_OBJ_OM_GETOBJECTLIST_MOD, TQ_OBJ_OM_GETOBJECTLIST, TQ_OBJ_OM_GETOBJECTLIST_REQ) \
    X(TQ_GAMEENGINE_GGAMEENGINE, TQ_GAMEENGINE_GGAMEENGINE_MOD, TQ_GAMEENGINE_GGAMEENGINE, TQ_GAMEENGINE_GGAMEENGINE_REQ) \
    X(TQ_GAMEENGINE_UPDATE, TQ_GAMEENGINE_UPDATE_MOD, TQ_GAMEENGINE_UPDATE, TQ_GAMEENGINE_UPDATE_REQ) \
    X(TQ_GAMEENGINE_GETMAINPLAYER, TQ_GAMEENGINE_GETMAINPLAYER_MOD, TQ_GAMEENGINE_GETMAINPLAYER, TQ_GAMEENGINE_GETMAINPLAYER_REQ) \
    X(TQ_GAMEENGINE_GETITEMCOLOR, TQ_GAMEENGINE_GETITEMCOLOR_MOD, TQ_GAMEENGINE_GETITEMCOLOR, TQ_GAMEENGINE_GETITEMCOLOR_REQ) \
    X(TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY, TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY_MOD, TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY, TQ_GAMEENGINE_GETITEMBACKGROUNDOPACITY_REQ) \
    X(TQ_GAMEENGINE_GETPLAYERSTASH, TQ_GAMEENGINE_GETPLAYERSTASH_MOD, TQ_GAMEENGINE_GETPLAYERSTASH, TQ_GAMEENGINE_GETPLAYERSTASH_REQ) \
    X(TQ_GAMEENGINE_GETPLAYERSTASH_C, TQ_GAMEENGINE_GETPLAYERSTASH_C_MOD, TQ_GAMEENGINE_GETPLAYERSTASH_C, TQ_GAMEENGINE_GETPLAYERSTASH_C_REQ) \
    X(TQ_GAMEENGINE_GETPLAYERTRANSFER, TQ_GAMEENGINE_GETPLAYERTRANSFER_MOD, TQ_GAMEENGINE_GETPLAYERTRANSFER, TQ_GAMEENGINE_GETPLAYERTRANSFER_REQ) \
    X(TQ_GAMEENGINE_GETPLAYERTRANSFER_C, TQ_GAMEENGINE_GETPLAYERTRANSFER_C_MOD, TQ_GAMEENGINE_GETPLAYERTRANSFER_C, TQ_GAMEENGINE_GETPLAYERTRANSFER_C_REQ) \
    X(TQ_GAMEENGINE_GETPLAYERRELICVAULT, TQ_GAMEENGINE_GETPLAYERRELICVAULT_MOD, TQ_GAMEENGINE_GETPLAYERRELICVAULT, TQ_GAMEENGINE_GETPLAYERRELICVAULT_REQ) \
    X(TQ_GAMEENGINE_GETPLAYERRELICVAULT_C, TQ_GAMEENGINE_GETPLAYERRELICVAULT_C_MOD, TQ_GAMEENGINE_GETPLAYERRELICVAULT_C, TQ_GAMEENGINE_GETPLAYERRELICVAULT_C_REQ) \
    X(TQ_GAMEENGINE_GETCARAVANMODE, TQ_GAMEENGINE_GETCARAVANMODE_MOD, TQ_GAMEENGINE_GETCARAVANMODE, TQ_GAMEENGINE_GETCARAVANMODE_REQ) \
    X(TQ_GAMEENGINE_SETCARAVANMODE, TQ_GAMEENGINE_SETCARAVANMODE_MOD, TQ_GAMEENGINE_SETCARAVANMODE, TQ_GAMEENGINE_SETCARAVANMODE_REQ) \
    X(TQ_GAMEENGINE_CARAVANGOODBYE, TQ_GAMEENGINE_CARAVANGOODBYE_MOD, TQ_GAMEENGINE_CARAVANGOODBYE, TQ_GAMEENGINE_CARAVANGOODBYE_REQ) \
    X(TQ_GAMEENGINE_ADDITEMTOSTASH_ID, TQ_GAMEENGINE_ADDITEMTOSTASH_ID_MOD, TQ_GAMEENGINE_ADDITEMTOSTASH_ID, TQ_GAMEENGINE_ADDITEMTOSTASH_ID_REQ) \
    X(TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID, TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID_MOD, TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID, TQ_GAMEENGINE_ADDITEMTOTRANSFER_ID_REQ) \
    X(TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID, TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID_MOD, TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID, TQ_GAMEENGINE_ADDITEMTORELICVAULT_ID_REQ) \
    X(TQ_GAMEENGINE_REMOVEITEMFROMSTASH, TQ_GAMEENGINE_REMOVEITEMFROMSTASH_MOD, TQ_GAMEENGINE_REMOVEITEMFROMSTASH, TQ_GAMEENGINE_REMOVEITEMFROMSTASH_REQ) \
    X(TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER, TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER_MOD, TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER, TQ_GAMEENGINE_REMOVEITEMFROMTRANSFER_REQ) \
    X(TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT, TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT_MOD, TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT, TQ_GAMEENGINE_REMOVEITEMFROMRELICVAULT_REQ) \
    X(TQ_NPC_ONPLAYERINTERACT, TQ_NPC_ONPLAYERINTERACT_MOD, TQ_NPC_ONPLAYERINTERACT, TQ_NPC_ONPLAYERINTERACT_REQ) \
    X(TQ_NPC_PLAYER_ISINMAINQUEST, TQ_NPC_PLAYER_ISINMAINQUEST_MOD, TQ_NPC_PLAYER_ISINMAINQUEST, TQ_NPC_PLAYER_ISINMAINQUEST_REQ) \
    X(TQ_CHAR_GETINVENTORYITEMS, TQ_CHAR_GETINVENTORYITEMS_MOD, TQ_CHAR_GETINVENTORYITEMS, TQ_CHAR_GETINVENTORYITEMS_REQ) \
    X(TQ_CTRL_GETCONTROLLERID, TQ_CTRL_GETCONTROLLERID_MOD, TQ_CTRL_GETCONTROLLERID, TQ_CTRL_GETCONTROLLERID_REQ) \
    X(TQ_CTRL_SENDREMOVEITEM, TQ_CTRL_SENDREMOVEITEM_MOD, TQ_CTRL_SENDREMOVEITEM, TQ_CTRL_SENDREMOVEITEM_REQ) \
    X(TQ_CTRL_PLAYER_VFTABLE, TQ_CTRL_PLAYER_VFTABLE_MOD, TQ_CTRL_PLAYER_VFTABLE, TQ_CTRL_PLAYER_VFTABLE_REQ) \
    X(TQ_CTRL_PLAYER_GETINVENTORYCTRL, TQ_CTRL_PLAYER_GETINVENTORYCTRL_MOD, TQ_CTRL_PLAYER_GETINVENTORYCTRL, TQ_CTRL_PLAYER_GETINVENTORYCTRL_REQ) \
    X(TQ_CTRL_INVCTRL_GETNUMBEROFSACKS, TQ_CTRL_INVCTRL_GETNUMBEROFSACKS_MOD, TQ_CTRL_INVCTRL_GETNUMBEROFSACKS, TQ_CTRL_INVCTRL_GETNUMBEROFSACKS_REQ) \
    X(TQ_CTRL_INVCTRL_GETSACK, TQ_CTRL_INVCTRL_GETSACK_MOD, TQ_CTRL_INVCTRL_GETSACK, TQ_CTRL_INVCTRL_GETSACK_REQ) \
    X(TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE, TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE_MOD, TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE, TQ_CTRL_PLAYER_ISINVENTORYSPACEAVAILABLE_REQ) \
    X(TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND, TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND_MOD, TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND, TQ_CTRL_PLAYER_PLAYINVENTORYFULLSOUND_REQ) \
    X(TQ_CTRL_CHAR_GETEQUIPMENTCTRL, TQ_CTRL_CHAR_GETEQUIPMENTCTRL_MOD, TQ_CTRL_CHAR_GETEQUIPMENTCTRL, TQ_CTRL_CHAR_GETEQUIPMENTCTRL_REQ) \
    X(TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET, TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET_MOD, TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET, TQ_CTRL_EQUIPCTRL_AREREQUIREMENTSMET_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_HEAD, TQ_CTRL_EQUIPCTRL_GETITEM_HEAD_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_HEAD, TQ_CTRL_EQUIPCTRL_GETITEM_HEAD_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_NECK, TQ_CTRL_EQUIPCTRL_GETITEM_NECK_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_NECK, TQ_CTRL_EQUIPCTRL_GETITEM_NECK_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT, TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT, TQ_CTRL_EQUIPCTRL_GETITEM_ARTIFACT_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY, TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY, TQ_CTRL_EQUIPCTRL_GETITEM_UPPERBODY_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY, TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY, TQ_CTRL_EQUIPCTRL_GETITEM_LOWERBODY_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1, TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1, TQ_CTRL_EQUIPCTRL_GETITEM_FINGER1_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2, TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2, TQ_CTRL_EQUIPCTRL_GETITEM_FINGER2_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM, TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM, TQ_CTRL_EQUIPCTRL_GETITEM_FOREARM_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT, TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT, TQ_CTRL_EQUIPCTRL_GETITEM_HANDLEFT_REQ) \
    X(TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT, TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT_MOD, TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT, TQ_CTRL_EQUIPCTRL_GETITEM_HANDRIGHT_REQ) \
    X(TQ_CURSOR_VFTABLE, TQ_CURSOR_VFTABLE_MOD, TQ_CURSOR_VFTABLE, TQ_CURSOR_VFTABLE_REQ) \
    X(TQ_CURSOR_GETID, TQ_CURSOR_GETID_MOD, TQ_CURSOR_GETID, TQ_CURSOR_GETID_REQ) \
    X(TQ_CURSOR_SETID, TQ_CURSOR_SETID_MOD, TQ_CURSOR_SETID, TQ_CURSOR_SETID_REQ) \
    X(TQ_CURSOR_PRIMARYSTASHACTIVATE, TQ_CURSOR_PRIMARYSTASHACTIVATE_MOD, TQ_CURSOR_PRIMARYSTASHACTIVATE, TQ_CURSOR_PRIMARYSTASHACTIVATE_REQ) \
    X(TQ_CURSOR_PRIMARYTRANSFERACTIVATE, TQ_CURSOR_PRIMARYTRANSFERACTIVATE_MOD, TQ_CURSOR_PRIMARYTRANSFERACTIVATE, TQ_CURSOR_PRIMARYTRANSFERACTIVATE_REQ) \
    X(TQ_CURSOR_PRIMARYRELICVAULTACTIVE, TQ_CURSOR_PRIMARYRELICVAULTACTIVE_MOD, TQ_CURSOR_PRIMARYRELICVAULTACTIVE, TQ_CURSOR_PRIMARYRELICVAULTACTIVE_REQ) \
    X(TQ_CURSOR_ISSTASHCAPABLE, TQ_CURSOR_ISSTASHCAPABLE_MOD, TQ_CURSOR_ISSTASHCAPABLE, TQ_CURSOR_ISSTASHCAPABLE_REQ) \
    X(TQ_CURSOR_ISTRANSFERCAPABLE, TQ_CURSOR_ISTRANSFERCAPABLE_MOD, TQ_CURSOR_ISTRANSFERCAPABLE, TQ_CURSOR_ISTRANSFERCAPABLE_REQ) \
    X(TQ_CURSOR_ISRELICVAULTCAPABLE, TQ_CURSOR_ISRELICVAULTCAPABLE_MOD, TQ_CURSOR_ISRELICVAULTCAPABLE, TQ_CURSOR_ISRELICVAULTCAPABLE_REQ) \
    X(TQ_SACK_ADDITEM, TQ_SACK_ADDITEM_MOD, TQ_SACK_ADDITEM, TQ_SACK_ADDITEM_REQ) \
    X(TQ_SACK_ADDITEM_VEC, TQ_SACK_ADDITEM_VEC_MOD, TQ_SACK_ADDITEM_VEC, TQ_SACK_ADDITEM_VEC_REQ) \
    X(TQ_SACK_REMOVEITEM, TQ_SACK_REMOVEITEM_MOD, TQ_SACK_REMOVEITEM, TQ_SACK_REMOVEITEM_REQ) \
    X(TQ_SACK_ISSPACEFORITEM, TQ_SACK_ISSPACEFORITEM_MOD, TQ_SACK_ISSPACEFORITEM, TQ_SACK_ISSPACEFORITEM_REQ) \
    X(TQ_SACK_GETITEMUNDERPOINT, TQ_SACK_GETITEMUNDERPOINT_MOD, TQ_SACK_GETITEMUNDERPOINT, TQ_SACK_GETITEMUNDERPOINT_REQ) \
    X(TQ_SACK_CTOR, TQ_SACK_CTOR_MOD, TQ_SACK_CTOR, TQ_SACK_CTOR_REQ) \
    X(TQ_SACK_VFTABLE, TQ_SACK_VFTABLE_MOD, TQ_SACK_VFTABLE, TQ_SACK_VFTABLE_REQ) \
    X(TQ_SACK_SORT, TQ_SACK_SORT_MOD, TQ_SACK_SORT, TQ_SACK_SORT_REQ) \
    X(TQ_SACK_SETDIMS, TQ_SACK_SETDIMS_MOD, TQ_SACK_SETDIMS, TQ_SACK_SETDIMS_REQ) \
    X(TQ_SACK_CONTAINSITEM, TQ_SACK_CONTAINSITEM_MOD, TQ_SACK_CONTAINSITEM, TQ_SACK_CONTAINSITEM_REQ) \
    X(TQ_SACK_GETCELLWIDTH, TQ_SACK_GETCELLWIDTH_MOD, TQ_SACK_GETCELLWIDTH, TQ_SACK_GETCELLWIDTH_REQ) \
    X(TQ_SACK_GETCELLHEIGHT, TQ_SACK_GETCELLHEIGHT_MOD, TQ_SACK_GETCELLHEIGHT, TQ_SACK_GETCELLHEIGHT_REQ) \
    X(TQ_SACK_GETGRIDWIDTH, TQ_SACK_GETGRIDWIDTH_MOD, TQ_SACK_GETGRIDWIDTH, TQ_SACK_GETGRIDWIDTH_REQ) \
    X(TQ_SACK_GETGRIDHEIGHT, TQ_SACK_GETGRIDHEIGHT_MOD, TQ_SACK_GETGRIDHEIGHT, TQ_SACK_GETGRIDHEIGHT_REQ) \
    X(TQ_SACK_GETINVENTORY, TQ_SACK_GETINVENTORY_MOD, TQ_SACK_GETINVENTORY, TQ_SACK_GETINVENTORY_REQ) \
    X(TQ_ITEM_VFTABLE, TQ_ITEM_VFTABLE_MOD, TQ_ITEM_VFTABLE, TQ_ITEM_VFTABLE_REQ) \
    X(TQ_ITEM_CREATEITEM, TQ_ITEM_CREATEITEM_MOD, TQ_ITEM_CREATEITEM, TQ_ITEM_CREATEITEM_REQ) \
    X(TQ_ITEM_GETITEMREPLICAINFO, TQ_ITEM_GETITEMREPLICAINFO_MOD, TQ_ITEM_GETITEMREPLICAINFO, TQ_ITEM_GETITEMREPLICAINFO_REQ) \
    X(TQ_ITEM_GETITEMCLASSIFICATION, TQ_ITEM_GETITEMCLASSIFICATION_MOD, TQ_ITEM_GETITEMCLASSIFICATION, TQ_ITEM_GETITEMCLASSIFICATION_REQ) \
    X(TQ_ITEM_GETITEMTYPE, TQ_ITEM_GETITEMTYPE_MOD, TQ_ITEM_GETITEMTYPE, TQ_ITEM_GETITEMTYPE_REQ) \
    X(TQ_ITEM_GETACTUALITEMCLASSIFICATION, TQ_ITEM_GETACTUALITEMCLASSIFICATION_MOD, TQ_ITEM_GETACTUALITEMCLASSIFICATION, TQ_ITEM_GETACTUALITEMCLASSIFICATION_REQ) \
    X(TQ_ITEM_GETNUMBERINSTACK, TQ_ITEM_GETNUMBERINSTACK_MOD, TQ_ITEM_GETNUMBERINSTACK, TQ_ITEM_GETNUMBERINSTACK_REQ) \
    X(TQ_TIP_ITEM_GETUIDISPLAYTEXT, TQ_TIP_ITEM_GETUIDISPLAYTEXT_MOD, TQ_TIP_ITEM_GETUIDISPLAYTEXT, TQ_TIP_ITEM_GETUIDISPLAYTEXT_REQ) \
    X(TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT, TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT_MOD, TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT, TQ_TIP_ITEMEQUIPMENT_GETUIDISPLAYTEXT_REQ) \
    X(TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT, TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT_MOD, TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT, TQ_TIP_ITEMARTIFACT_GETUIDISPLAYTEXT_REQ) \
    X(TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT, TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT_MOD, TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT, TQ_TIP_ITEMRELIC_GETUIDISPLAYTEXT_REQ) \
    X(TQ_TIP_GAMETEXTLINETOSTRING, TQ_TIP_GAMETEXTLINETOSTRING_MOD, TQ_TIP_GAMETEXTLINETOSTRING, TQ_TIP_GAMETEXTLINETOSTRING_REQ) \
    X(TQ_TIP_GAMETEXTLINE_CTOR, TQ_TIP_GAMETEXTLINE_CTOR_MOD, TQ_TIP_GAMETEXTLINE_CTOR, TQ_TIP_GAMETEXTLINE_CTOR_REQ) \
    X(TQ_CRT_OPERATORDELETE, TQ_CRT_OPERATORDELETE_MOD, TQ_CRT_OPERATORDELETE, TQ_CRT_OPERATORDELETE_REQ)
